/**
 * JavaScript implement tag based input field using jQuery or fusionLib.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 *
 * @package fusionCSS
 * @copyright Copyright (c) 2019 fusionCSS. All rights reserved.
 * @link http://fusionCSS.com
 */
!function(){var t=null;function e(t,e){return t.val().split(t.attr("data-delimiter")).indexOf(e)>-1}function a(t,e,a){e.val(""),$("#"+e.attr("id")+"_tagInputWidget .tag").remove();for(var i=a.split(e.attr("data-delimiter")),n=0;n<i.length;n++)l(t,e,i[n],!1);return e}function l(t,a,l,i){if((l=l.trim()).length){var n=l.split(a.attr("data-delimiter")),r=a.val().split(a.attr("data-delimiter")),d=$("#"+a.attr("id")+"_tagInput");""==r[0]&&(r=new Array);for(var g=0;g<n.length;g++)e(a,l=n[g])?0===n.length&&d.addClass("invalidTag"):(d.removeClass("invalidTag").val(""),$(t.tagHTML.replace(/\{value\}/g,(s=l,String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")))).insertBefore(d),i?d.focus():d.blur(),r.push(l),a.val(r.join(a.attr("data-delimiter"))))}var s}function i(t,e,l){var i=e.attr("data-delimiter"),n=e.val().split(i),r=n.indexOf(l);r>-1&&(n.splice(r,1),a(t,e,n.join(i)))}$.fn.extend({setTags:function(t){return a(this,t)},enableTagInput:function(e){var n=$.extend({tagHTML:'<div class="chip tag"><span class="tagValue">{value}</span><i class="tagDelete">x</i></div>',widgetHTML:'<div id="{id}_tagInputWidget" class="tagInputWidget"><input id="{id}_tagInput" class="tagInput" value="" placeholder="{placeholder}" /></div>'},e);return this.each((function(){var e=$(this),r=e.attr("id"),d=e.attr("data-delimiter");e.attr("data-init-done")||(e.attr("data-init-done","1").hide(),$(n.widgetHTML.replace(/\{id\}/g,r).replace(/\{placeholder\}/g,e.attr("data-placeholder"))).insertAfter(e),a(n,e,e.val()),$("#"+r+"_tagInputWidget").on("click",(function(t){$(t.target).closest(".tagDelete").length?(t.preventDefault(),i(n,e,$(t.target).closest(".tag").find(".tagValue").text())):$("#"+r+"_tagInput").focus()})),$("#"+r+"_tagInput").on("blur",(function(t){l(n,e,$("#"+r+"_tagInput").val(),!0)})).on("keydown",(function(a){var r=$(this);if(r.removeClass("invalidTag"),"Enter"===a.key||a.key===d)a.preventDefault(),l(n,e,r.val(),!0);else if("Backspace"===a.key&&""===r.val())a.preventDefault(),i(n,e,r.closest(".tagInputWidget").find(".tag").last().find(".tagValue").text()),r.focus();else if((a.ctrlKey||a.metaKey)&&"c"===a.key&&0===r.val().length){a.preventDefault(),t||(t=$('<textarea style="position:absolute; left:-9999px; top:0">'),$("body").append(t)),t.val(e.val()).focus()[0].setSelectionRange(0,t.val().length);try{document.execCommand("copy")}catch(t){}r.focus()}})))}))}})}();
//# sourceMappingURL=fusionCSSTagInput.js.map
